//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTourDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Tour_id { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> Vote { get; set; }
    
        public virtual Tour Tour { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
