//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTourDuLich.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLy_TourDuLichEntities : DbContext
    {
        public QuanLy_TourDuLichEntities()
            : base("name=QuanLy_TourDuLichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTiet_DatTour> ChiTiet_DatTour { get; set; }
        public virtual DbSet<DanhGia> DanhGia { get; set; }
        public virtual DbSet<DatTour> DatTour { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<HuongDanVien> HuongDanVien { get; set; }
        public virtual DbSet<Image_Tour> Image_Tour { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<Loai_Tour> Loai_Tour { get; set; }
        public virtual DbSet<PhanCong_HuongDanVien> PhanCong_HuongDanVien { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<ThanhToan> ThanhToan { get; set; }
    }
}
