//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTourDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int id { get; set; }
        public Nullable<int> DatTour_id { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual DatTour DatTour { get; set; }
    }
}
