//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTourDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.ChiTiet_DatTour = new HashSet<ChiTiet_DatTour>();
            this.DanhGia = new HashSet<DanhGia>();
            this.Image_Tour = new HashSet<Image_Tour>();
            this.PhanCong_HuongDanVien = new HashSet<PhanCong_HuongDanVien>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Gia { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string LichTrinh { get; set; }
        public string DiemKhoiHanh { get; set; }
        public string DiemDen { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoLuongCon { get; set; }
        public Nullable<int> Loai_Tour_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_DatTour> ChiTiet_DatTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image_Tour> Image_Tour { get; set; }
        public virtual Loai_Tour Loai_Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCong_HuongDanVien> PhanCong_HuongDanVien { get; set; }
    }
}
